[package]
name = "rusty_micromu"
version = "0.1.0"
authors = ["Amejonah1200"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
enum_primitive = "*"
num = "0.2.1"
